DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS movie_track;
CREATE TABLE tracks(tId INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, author TEXT, album TEXT, duration INTEGER);
CREATE TABLE movie_track(mId INTEGER, tId INTEGER, PRIMARY KEY(mId, tId));
INSERT INTO movie_track VALUES(1,1);
INSERT INTO movie_track VALUES(1,2);
INSERT INTO movie_track VALUES(2,1);
INSERT INTO movie_track VALUES(2,3);
INSERT INTO movie_track VALUES(3,3);
INSERT INTO movie_track VALUES(3,2);
INSERT INTO tracks VALUES("Epic (Original Mix)","Sandro Silva & Quintino","Trance Essentials 2012, Vol. 1 (Unmixed)",360)
INSERT INTO tracks VALUES("Ping Pong (Radio Edit)","Armin van Buuren","A State Of Trance 2014 (Unmixed)",179)
INSERT INTO tracks VALUES("Electro Trance (Fullon Psytrance Mix)","Phoenix","100 Hard Trance Hits 2014",429)
INSERT INTO tracks VALUES("Free tibet","Hilight Tribe","Love medicine & natural trance",359)
INSERT INTO tracks VALUES("EIFORYA (Intro Radio Edit)","Armin van Buuren","A State Of Trance 2014 (Unmixed)",167)
INSERT INTO tracks VALUES("Haunted (Radio Edit)","Marlo","A State Of Trance 2014 (Unmixed)",247)
INSERT INTO tracks VALUES("In Trance (Studio Edit)","Scorpions","MTV Unplugged (The Studio Edits)",231)
INSERT INTO tracks VALUES("Stop Pushing (Hard Psytrance Mix)","Phoenix","100 Hard Trance Hits 2014",346)
INSERT INTO tracks VALUES("Visions (Radio Edit)","Marlo","A State Of Trance 2014 (Unmixed)",201)
INSERT INTO tracks VALUES("Stop Pushing (2013 Mix)","Phoenix","Decade of Deca-dance 1 - 10 years of Psychedelic Goa Techno Trance Evolution (2004-2014)",546)
INSERT INTO tracks VALUES("The Tube (Max Angel Remix)","DJ Tiësto","Trance Raider - Tomb 6",467)
INSERT INTO tracks VALUES("In Trance (Studio Edit)","Scorpions","MTV Unplugged (The Studio Edits)",231)
INSERT INTO tracks VALUES("Ping Pong [Mix Cut] (Original Mix)","Armin van Buuren","A State Of Trance 2014 (Mixed Version)",405)
INSERT INTO tracks VALUES("Save My Night (Original Mix)","Armin van Buuren","A State Of Trance Radio Top 20 - January 2014 (Including Classic Bonus Track)",337)
INSERT INTO tracks VALUES("U (Bryan Kearney Radio Edit)","Gareth Emery","A State Of Trance 2014 (Unmixed)",252)
INSERT INTO tracks VALUES("Samba trance (Original)","Hilight Tribe","Limboland",239)
INSERT INTO tracks VALUES("Everything (Pedro Del Mar & Doublev Remix)","Tiësto","Miami Vocal Trance Essentials 2014",453)
INSERT INTO tracks VALUES("Save My Night [Mix Cut] (MaRLo Remix)","Armin van Buuren","Armada Trance 2014-001 (Mixed Version)",198)
INSERT INTO tracks VALUES("Save My Night (Allen Watts Radio Edit)","Armin van Buuren","A State Of Trance 2014 (Unmixed)",187)
INSERT INTO tracks VALUES("Marijuana (Live Remix) [feat. Cortex & Didrapest]","1200 Micrograms","101 Psychedelic Dance Hits 2013 - Best of Top New Goa Psy Trance, Hard Electronica, Rave Anthems, Acid House, Electro, Hard Style",385)
INSERT INTO tracks VALUES("My Heaven (Radio Edit)","Alex M.O.R.P.H.","A State Of Trance 2014 (Unmixed)",222)
INSERT INTO tracks VALUES("EIFORYA [Mix Cut] (Intro Mix)","Armin van Buuren","A State Of Trance 2014 (Mixed Version)",320)
INSERT INTO tracks VALUES("EIFORYA [Mix Cut] (Original Mix)","Armin van Buuren","Armada Trance 2014-001 (Mixed Version)",149)
INSERT INTO tracks VALUES("Zybex - Saico Psybex - 145 - [ Trance / Goa / Fullon ]","DJ Electronica Trance","69 Electronica (Best of Top Electronic Dance Music, Goa, Techno, Psytrance, Acid House, Hard Dance, Trance Anthems, Dubstep Hits)",504)
INSERT INTO tracks VALUES("Different (Original Mix)","Eve","Appointed Recordings London Underground Trance 001",400)
INSERT INTO tracks VALUES("Saltwater [Mix Cut] (Original Mix)","Chicane","A State Of Trance 650 - New Horizons",134)
INSERT INTO tracks VALUES("Electro Trance","Phoenix","101 Edm Rave Hits 2013 - Top Electronica Workout, Dubstep, Trap, Electro, Techno, Goa, Trance Anthems",429)
INSERT INTO tracks VALUES("Haunted [Mix Cut] (Original Mix)","Marlo","A State Of Trance 2014 (Mixed Version)",212)
INSERT INTO tracks VALUES("Goodbye (Radio Edit)","Andrew Rayel","A State Of Trance 2014 (Unmixed)",190)
INSERT INTO tracks VALUES("We Are Here To Make Some Noise (Extended Mix)","Armin van Buuren","A State Of Trance Radio Top 20 - June 2012 (Including Classic Bonus Track)",312)
INSERT INTO tracks VALUES("Ping Pong [Mix Cut] (Simon Patterson Remix)","Armin van Buuren","Armada Trance 2014-001 (Mixed Version)",206)
INSERT INTO tracks VALUES("Athena (Radio Edit)","Dart Rayne","A State Of Trance 2014 (Unmixed)",228)
INSERT INTO tracks VALUES("My Heaven [Mix Cut] (Original Mix)","Alex M.O.R.P.H.","A State Of Trance 2014 (Mixed Version)",218)
INSERT INTO tracks VALUES("For An Angel [Mix Cut] (PvD E-Werk Club Mix)","Paul van Dyk","A State Of Trance 650 - New Horizons",113)
INSERT INTO tracks VALUES("Flash (Original Mix)","Eve","Appointed Recordings London Underground Trance 001",278)
INSERT INTO tracks VALUES("Crying Freemen - Icontol - 145 - [ Trance / Goa / Fullon ]","DJ Electronica Trance","69 Electronica (Best of Top Electronic Dance Music, Goa, Techno, Psytrance, Acid House, Hard Dance, Trance Anthems, Dubstep Hits)",477)
INSERT INTO tracks VALUES("Save My Night [Mix Cut] (Allen Watts Remix)","Armin van Buuren","A State Of Trance 2014 (Mixed Version)",306)
INSERT INTO tracks VALUES("Never Say Goodbye (Radio Edit)","Hardwell and Dyro featuring Bright Lights","Trance The Ultimate Collection Vol 3 2013",204)
INSERT INTO tracks VALUES("U [Mix Cut] (Bryan Kearney Remix)","Gareth Emery","A State Of Trance 2014 (Mixed Version)",337)
INSERT INTO tracks VALUES("Beyond The Stars (Original Mix)","Kelly Andrew","A State Of Trance Radio Top 20 - December 2013 (Including Classic Bonus Track)",524)
INSERT INTO tracks VALUES("Destino","Markus Schulz","A State Of Trance 2014 (Unmixed)",279)
INSERT INTO tracks VALUES("Athena [Mix Cut] (Original Mix)","Dart Rayne","A State Of Trance 2014 (Mixed Version)",178)
INSERT INTO tracks VALUES("In God We Trust","Dream Techno","Trance Of House",289)
INSERT INTO tracks VALUES("Summer Days","Soom T","HADRA TRANCE FESTIVAL 2013",216)
INSERT INTO tracks VALUES("End Of The Road (Hazem Beltagui Radio Edit)","Aly & Fila","A State Of Trance 2014 (Unmixed)",254)
INSERT INTO tracks VALUES("The Late Anthem (Way Too Late Radio Edit)","Orjan Nilsen","A State Of Trance 2014 (Unmixed)",145)
INSERT INTO tracks VALUES("RAMelia (Tribute To Amelia) (Radio Edit)","Ram","A State Of Trance 2014 (Unmixed)",205)
INSERT INTO tracks VALUES("Goodbye [Mix Cut] (Original Mix)","Andrew Rayel","A State Of Trance 2014 (Mixed Version)",179)
INSERT INTO tracks VALUES("Decibels (Original Mix Edit)","Craig Connelly","A State Of Trance 2014 (Unmixed)",263)
INSERT INTO tracks VALUES("Visions [Mix Cut] (Original Mix)","Marlo","A State Of Trance 2014 (Mixed Version)",191)
